# fp = open("filex.txt","r")
# contant = fp.read()
# # contant1 = fp.readline()
# # con2 = fp.readline()
# # print(contant1,con2)
# # c = fp.readlines()
# # print(c)
# print(contant)
f = open("multiple_str.txt","r")
s = f.read()
print(s)
f.close()